version: '2.2'
services:
  tokenizer:
    build: 158_tokenizer
    init: true
    volumes:
    - './158-docker.ini:/usr/src/app/158.ini:ro'
    ports:
    - '5001:5001'
  disambiguator:
    build: 158_disambiguator
    init: true
    environment:
    - LANGUAGE=en
    volumes:
    - './158-docker.ini:/usr/src/app/158.ini:ro'
    ports:
    - '5002:5002'
  frontend:
    build: 158_frontend
    init: true
    ports:
    - '5000:5000'
    volumes:
    - './158-docker.ini:/usr/src/app/158.ini:ro'
    links:
    - tokenizer
    - disambiguator
