version: '2.2'
services:
  tokenizer:
    build: 158_tokenizer
    init: true
    volumes:
    - './158-docker.ini:/usr/src/app/158.ini:ro'
    - './158_tokenizer/stanford_segmenter:/usr/src/app/stanford_segmenter:ro'
    - './158_tokenizer/UETSegmenter:/usr/src/app/UETSegmenter:ro'
    ports:
    - '10151:5001'
  disambiguator:
    build: 158_disambiguator
    init: true
    environment:
    - LANGUAGE=en
    volumes:
    - './158-docker.ini:/usr/src/app/158.ini:ro'
    - './158_disambiguator/models:/usr/src/app/models:ro'
    ports:
    - '10152:5002'
  frontend:
    build: 158_frontend
    init: true
    ports:
    - '10150:5000'
    volumes:
    - './158-docker.ini:/usr/src/app/158.ini:ro'
    links:
    - tokenizer
    - disambiguator
